App\Entity\User:
  attributes:
    id:
      groups: ['user_read', 'expense_read']
    name:
      groups: ['user_read', 'user_post', 'user_put', 'expense_read']
    email:
      groups: ['user_read', 'user_post', 'user_put', 'expense_read']
    password:
      groups: ['user_post']
    roles:
      groups: ['user_read', 'user_put']
    createdAt:
      groups: ['user_read']
    updatedAt:
      groups: ['user_read']