App\Entity\User:
  attributes:
    id:
      groups: ['user_read', 'expense_read']
    name:
      groups: ['user_read', 'user_write', 'expense_read']
    email:
      groups: ['user_read', 'expense_read']
    password:
      groups: ['user_write']
    roles:
      groups: ['user_read', 'user_write']
    createdAt:
      groups: ['user_read']
    updatedAt:
      groups: ['user_read']